branchs:
    only:
        - master

language: android

android:
    components:
        - build-tools-23.0.0
        - android-22
        - extra-android-support
        - extra-android-m2repository
cache:
  directories:
    - $HOME/.gradle
    - $HOME/.m2/repository